import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import PublicHeader from "@/components/layouts/PublicHeader";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <PublicHeader></PublicHeader>
    {children}
    </>
  );
}
